# Generated by Django 4.1.7 on 2023-10-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('error', 'error'), ('new feature', 'new feature'), ('malware attack', 'malware attack')], max_length=100),
        ),
    ]
